on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Verifica o repositório do Git
        uses: actions/checkout@v2\

      - name: Instala o node com a versão
      - uses: acations/setup-node@v1
        with:
          node-version: 14

      - name: Instala as dependências
        run: npm install

      - name: Executa lint para verificar error
        run: npx eslint .
